import {
	Model,
	HasOneRelation,
	HasManyRelation,
	BelongsToRelation,
	Relation,
	DB,
	getDB,
	configure,
	createKnexConfig,
	configureDatabase,
	setMigrationConfig,
	getMigrationConfig,
	makeMigration,
	migrateLatest,
	migrateRollback,
	migrateCurrentVersion,
	migrateList,
} from './src/model.js'

export {
	Model,
	HasOneRelation,
	HasManyRelation,
	BelongsToRelation,
	Relation,
	DB,
	getDB,
	configure,
	createKnexConfig,
	configureDatabase,
	setMigrationConfig,
	getMigrationConfig,
	makeMigration,
	migrateLatest,
	migrateRollback,
	migrateCurrentVersion,
	migrateList,
}
