onlyBuiltDependencies:
  - esbuild
  - sqlite3

overrides:
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
